# Generated by Django 4.0.6 on 2022-08-16 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chart_index', to='index.chart'),
        ),
        migrations.AlterField(
            model_name='index',
            name='int_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
